version: '3.1'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - '3307:3306'
    volumes:
      - $HOME/Documents/MySQL-Snippets/python.sql:/python.sql
